package com.leaprnd.observer4j;

public enum ForwardStrategy {
	FORWARD_AFTER_MARKING_FIELD_AS_ACCESSED,
	FORWARD_AFTER_MARKING_EVERY_FIELD_AS_ACCESSED,
	FORWARD_WITHOUT_MARKING_ANY_FIELDS_AS_ACCESSED,
	DO_NOT_FORWARD
}